// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNKteVH_KWklMxU40k3eN60bAXkI3h2Zk',
    appId: '1:1095590355212:web:e5e9f83024fad163e7a929',
    messagingSenderId: '1095590355212',
    projectId: 'navtj-61c6a',
    authDomain: 'navtj-61c6a.firebaseapp.com',
    storageBucket: 'navtj-61c6a.appspot.com',
    measurementId: 'G-8WYX455L67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1j9KRxEagsv1h9xdwE9uoNLKhRmGB9ng',
    appId: '1:1095590355212:android:0f15ece78d107653e7a929',
    messagingSenderId: '1095590355212',
    projectId: 'navtj-61c6a',
    storageBucket: 'navtj-61c6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByI-nThcTnTxkda7iJZ1n743wBgl6gmmw',
    appId: '1:1095590355212:ios:a28298eea6107a9ce7a929',
    messagingSenderId: '1095590355212',
    projectId: 'navtj-61c6a',
    storageBucket: 'navtj-61c6a.appspot.com',
    iosClientId: '1095590355212-11177ti6r0mna0l8gk4usa8dmg1q3fd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tjScavengerDraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByI-nThcTnTxkda7iJZ1n743wBgl6gmmw',
    appId: '1:1095590355212:ios:5b7e598640c251f3e7a929',
    messagingSenderId: '1095590355212',
    projectId: 'navtj-61c6a',
    storageBucket: 'navtj-61c6a.appspot.com',
    iosClientId: '1095590355212-gdpj65pgjljf2gdrrbsoovesg9jmlstv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tjScavengerDraft.RunnerTests',
  );
}
