import 'package:flutter/material.dart';
import 'tsd_locations.dart';

//List<String> roomNumsList = ['kitchen', 'living room','220', '221','222','223'];
List<Location> roomList = [
  Location.supersimple('Second Floor Pool :)')
,Location.supersimple('Auditorium Lobby')
,Location.supersimple('120')
,Location.supersimple('Auditorium Staircase')
,Location.supersimple('Band Hallway')
,Location.supersimple('131')
,Location.supersimple('134')
,Location.supersimple('135')
,Location.supersimple('Nobel Commons')
,Location.supersimple('Admin')
,Location.supersimple('Front Office')
,Location.supersimple('Dome')
,Location.supersimple('115')
,Location.supersimple('115B')
,Location.supersimple('115C')
,Location.supersimple('68')
,Location.supersimple('Art Gallery')
,Location.supersimple('PCR')
,Location.supersimple('118')
,Location.supersimple('111')
,Location.supersimple('113')
,Location.supersimple('Nobel Staircase')
,Location.supersimple('Galileo Commons')
,Location.supersimple('67')
,Location.supersimple('12')
,Location.supersimple('11')
,Location.supersimple('14')
,Location.supersimple('15')
,Location.supersimple('DaVinci Commons')
,Location.supersimple('3')
,Location.supersimple('4')
,Location.supersimple('5')
,Location.supersimple('6')
,Location.supersimple('7')
,Location.supersimple('8')
,Location.supersimple('9')
,Location.supersimple('10')
,Location.supersimple('DaVinci Staircase')
,Location.supersimple('Lost and Found')
,Location.supersimple('Quantum Staircase')
,Location.supersimple('Fish Staircase')
,Location.supersimple('Cafeteria')
,Location.supersimple('2')
,Location.supersimple('16')
,Location.supersimple('17')
,Location.supersimple('Turing Commons')
,Location.supersimple('25')
,Location.supersimple('26')
,Location.supersimple('27')
,Location.supersimple('28')
,Location.supersimple('29')
,Location.supersimple('30')
,Location.supersimple('31')
,Location.supersimple('32')
,Location.supersimple('33')
,Location.supersimple('34')
,Location.supersimple('36')
,Location.supersimple('Turing Elevator')
,Location.supersimple('23')
,Location.supersimple('37')
,Location.supersimple('38')
,Location.supersimple('39')
,Location.supersimple('Turing Hallway')
,Location.supersimple('22')
,Location.supersimple('18')
,Location.supersimple('Turing Staircase')
,Location.supersimple('Door 6')
,Location.supersimple('40')
,Location.supersimple('42')
,Location.supersimple('44')
,Location.supersimple('45')
,Location.supersimple('46')
,Location.supersimple('48')
,Location.supersimple('Einstein Commons')
,Location.supersimple('50')
,Location.supersimple('51')
,Location.supersimple('52')
,Location.supersimple('53')
,Location.supersimple('54')
,Location.supersimple('47')
,Location.supersimple('56')
,Location.supersimple('57')
,Location.supersimple('Einstein Staircase')
,Location.supersimple('Language Hallway 1')
,Location.supersimple('69')
,Location.supersimple('70')
,Location.supersimple('71')
,Location.supersimple('73')
,Location.supersimple('74')
,Location.supersimple('75')
,Location.supersimple('Language Hallway 2')
,Location.supersimple('2')
,Location.supersimple('66')
,Location.supersimple('65')
,Location.supersimple('64')
,Location.supersimple('62')
,Location.supersimple('61')
,Location.supersimple('60')
,Location.supersimple('Language Hallway Staircase')
,Location.supersimple('Darwin Commons')
,Location.supersimple('77')
,Location.supersimple('80')
,Location.supersimple('81')
,Location.supersimple('Planetarium')
,Location.supersimple('58')
,Location.supersimple('59')
,Location.supersimple('Faraday Commons')
,Location.supersimple('83')
,Location.supersimple('84')
,Location.supersimple('85')
,Location.supersimple('86')
,Location.supersimple('87')
,Location.supersimple('82')
,Location.supersimple('Faraday Staircase')
,Location.supersimple('Gym 2')
,Location.supersimple('Gandhi Commons')
,Location.supersimple('105')
,Location.supersimple('106')
,Location.supersimple('107')
,Location.supersimple('109')
,Location.supersimple('103')
,Location.supersimple('104')
,Location.supersimple('Gym 1')
,Location.supersimple('Door 9')
,Location.supersimple('88')
,Location.supersimple('89')
,Location.supersimple('Weight Room')
,Location.supersimple('Boy\'s Team Room')
,Location.supersimple('Girl\'s Team Room')
,Location.supersimple('Franklin Commons')
,Location.supersimple('224')
,Location.supersimple('225')
,Location.supersimple('226')
,Location.supersimple('227')
,Location.supersimple('Black Box/228')
,Location.supersimple('Student Services')
,Location.supersimple('Franklin Staircase')
,Location.supersimple('Nobel Staircase')
,Location.supersimple('Nobel Balcony')
,Location.supersimple('219')
,Location.supersimple('Newton Commons')
,Location.supersimple('216')
,Location.supersimple('217')
,Location.supersimple('218')
,Location.supersimple('215')
,Location.supersimple('214')
,Location.supersimple('211')
,Location.supersimple('212')
,Location.supersimple('Curie Commons')
,Location.supersimple('200')
,Location.supersimple('201')
,Location.supersimple('202')
,Location.supersimple('203')
,Location.supersimple('206')
,Location.supersimple('207')
,Location.supersimple('208')
,Location.supersimple('Curie Staircase')
,Location.supersimple('Robotics Staircase')
,Location.supersimple('Gabor Staircase')
,Location.supersimple('Library')
,Location.supersimple('Library Hallway')
,Location.supersimple('Library Staircase')
,Location.supersimple('Hopper Commons ')
,Location.supersimple('229')
,Location.supersimple('230')
,Location.supersimple('231')
,Location.supersimple('232')
,Location.supersimple('233')
,Location.supersimple('234')
,Location.supersimple('235')
,Location.supersimple('236')
,Location.supersimple('237')
,Location.supersimple('238')
,Location.supersimple('Hopper Elevator')
,Location.supersimple('239')
,Location.supersimple('240')
,Location.supersimple('Hopper Staircase')
,Location.supersimple('Lecture Hall')
,Location.supersimple('241 (Lecture Hall)')
,Location.supersimple('242')
,Location.supersimple('243')
,Location.supersimple('244')
,Location.supersimple('245')
,Location.supersimple('Tesla Commons')
,Location.supersimple('246')
,Location.supersimple('247')
,Location.supersimple('248')
,Location.supersimple('249')
,Location.supersimple('250')
,Location.supersimple('251')
,Location.supersimple('252')
,Location.supersimple('253')
,Location.supersimple('Tesla Staircase')
,Location.supersimple('Carson Commons')
,Location.supersimple('278')
,Location.supersimple('281')
,Location.supersimple('282')
,Location.supersimple('254')
,Location.supersimple('255')
,Location.supersimple('Carver Commons')
,Location.supersimple('283')
,Location.supersimple('284')
,Location.supersimple('285')
,Location.supersimple('286')
,Location.supersimple('287')
,Location.supersimple('Carver Staircase')

];